"""
Django settings for sims project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR C:\Users\冰\Desktop\SIMS3\sims

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7@qestxo0iembfwx5^!ta9th!_lg45tv0-&z8ae&13p)-%64oy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'sims3',
    'bootstrap4',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',  # for handling : 127.0.0.1 refused to connect.
]

ROOT_URLCONF = 'sims.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # templates / template
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sims.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
        'NAME': 'simsdb',  # 数据库名称
        'USER': 'root',  # 连接数据库的用户名称
        'PASSWORD': '010209',  # 用户密码
        'HOST': '127.0.0.1',  # 访问的数据库的主机的ip地址
        'PORT': '3306',  # 默认mysql访问端口
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'zh-Hans'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "sims3/templates/manages",
    # os.path.join(BASE_DIR, 'static')
]
# print(STATICFILES_DIRS) [WindowsPath('C:/Users/冰/Desktop/SIMS3/sims/sims3/templates/manages')]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LOGGING = {
#     'version': 1,  # 指明dictConnfig的版本，目前就只有一个版本
#     'disable_existing_loggers': False,  # 禁用所有的已经存在的日志配置
#
#     # 格式器
#     'formatters': {
#         'standard': {  # 详细
#             'format': '\n%(asctime)s %(levelname)s %(pathname)s %(funcName)s] \n'
#                       '%(lineno)d %(message)s\n'
#                       '\n------------------------------------------------------------',
#         },
#         'simple': {  # 简单
#             'format': '时间:%(asctime)s | %(levelname)s | %(message)s',
#         },
#     },
#
#     # 过滤器
#     'filters': {
#         'require_debug_true': {
#             '()': 'django.utils.log.RequireDebugTrue',  # 此过滤器仅在settings.DEBUG为True时传递记录
#         },
#         'require_debug_false': {
#             '()': 'django.utils.log.RequireDebugFalse',  # 此过滤器仅在settings.DEBUG为False时传递记录
#         },
#     },
#
#     # 处理器，在这里定义了三个处理器。主要指明：处理引擎类、格式器、过滤器、日志等级
#     'handlers': {
#         'file_handler': {  # 文件处理器，所有高于(包括)debug的消息会被传到C:\Users\冰\Desktop\log.txt'
#             'level': 'DEBUG',
#             'class': 'logging.handlers.TimedRotatingFileHandler',
#             'formatter': 'standard',
#             'filename': r'C:\Users\冰\Desktop\log.txt',
#         },
#         # 'console': {  # 流处理器(控制台)，所有的高于(包括)debug的消息会被传到stderr，使用的是simple格式器
#         #     'level': 'INFO',
#         #     'class': 'logging.StreamHandler',
#         #     'formatter': 'standard',
#         # },
#         'mail_admins': {  # AdminEmail处理器，所有高于(包括)而error的消息会被发送给站点管理员，使用的是special格式器
#             'level': 'ERROR',
#             'class': 'django.utils.log.AdminEmailHandler',
#             'formatter': 'standard',
#             'include_html': False,  # 是否发送那些回溯信息，因为这些都是很敏感的系统系统，如果被人截获，可能会发生危险，所以要谨慎
#             'filters': ['require_debug_false'],  # 当settings.DEBUG=False的时候，AdminEmailHandler才生效
#         },
#     },
#
#     # 记录器。主要指明：处理器、日志等级
#     'loggers': {
#         'django': {  # 使用file_handler处理器，所有高于(包括)info的消息会被发往console和file_handler处理器，向父层次传递信息
#             # 'handlers': ['file_handler', 'console'],
#             'handlers': ['file_handler'],
#             'level': 'INFO',
#             'propagate': False,  # 是否继承父类的log信息
#         },
#         'django.request': {  # 所有高于(包括)error的消息会被发往console和mail_admins处理器，消息不向父层次发送
#             # 'handlers': ['mail_admins', 'console'],
#             'handlers': ['mail_admins'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#         'myproject.custom': {  # 所有高于(包括)info的消息同时会被发往console和mail_admins处理器
#             'handlers': ['mail_admins'],
#             # 'handlers': ['mail_admins', 'console'],
#             'level': 'INFO',
#             'propagate': False,
#         },
#     }
# }
# AUTH_USER_MODEL = 'sims3.Users'