# Generated by Django 3.2.7 on 2021-09-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims3', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='user',
        ),
    ]
